import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { portfolioData as data } from './data/portfolioData'
import Icon from './components/Icon'

const reveal = { hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0, transition: { duration: 0.65, ease: [0.22, 1, 0.36, 1] } } }
const stagger = { hidden: {}, show: { transition: { staggerChildren: 0.08 } } }

function SectionHeading({ kicker, title, intro }) {
  return <motion.div className="section-heading" variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.2 }}>
    <span className="kicker">{kicker}</span><h2>{title}</h2>{intro && <p>{intro}</p>}
  </motion.div>
}

function Counter({ value }) {
  const [count, setCount] = useState(0)
  useEffect(() => {
    const target = Number.parseInt(value, 10)
    if (Number.isNaN(target)) return undefined
    let current = 0
    const timer = window.setInterval(() => {
      current += 1
      setCount(current)
      if (current >= target) window.clearInterval(timer)
    }, 80)
    return () => window.clearInterval(timer)
  }, [value])
  const suffix = value.replace(/[0-9]/g, '')
  return <>{Number.isNaN(Number.parseInt(value, 10)) ? value : `${count}${suffix}`}</>
}

function Navbar() {
  const [open, setOpen] = useState(false)
  const links = ['About', 'Skills', 'Services', 'Projects', 'Experience', 'Education', 'Contact']
  return <header className="navbar"><a className="logo" href="#home">Akaash<span>.dev</span></a><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}><Icon name={open ? 'x' : 'menu'} /></button><nav className={open ? 'nav-links open' : 'nav-links'}><a href="#home" onClick={() => setOpen(false)}>Home</a>{links.map(link => <a key={link} href={`#${link.toLowerCase()}`} onClick={() => setOpen(false)}>{link}</a>)}<a href="#contact" className="nav-cta" onClick={() => setOpen(false)}>Hire Me <Icon name="arrow" size={15} /></a></nav></header>
}

function Hero() {
  return <section className="hero page-section" id="home"><div className="hero-copy"><motion.div initial="hidden" animate="show" variants={stagger}><motion.div className="status-pill" variants={reveal}><span /> Available for Freelance Projects</motion.div><motion.p className="hero-eyebrow" variants={reveal}>{data.hero.eyebrow} <span>👋</span></motion.p><motion.h1 variants={reveal}>Freelance Web Developer <em>&</em> AI/ML Enthusiast</motion.h1><motion.p className="hero-description" variants={reveal}>{data.hero.description}</motion.p><motion.div className="hero-actions" variants={reveal}><a className="button button-primary" href="#projects">View My Work <Icon name="arrow" size={17} /></a><a className="button button-ghost" href="#contact">Hire Me <Icon name="arrow" size={17} /></a></motion.div><motion.div className="social-row" variants={reveal}><a href="https://github.com" aria-label="GitHub"><Icon name="github" /></a><a href="https://linkedin.com" aria-label="LinkedIn"><Icon name="linkedin" /></a><a href={`mailto:${data.email}`} aria-label="Email"><Icon name="mail" /></a><a href="https://wa.me/919578448321" aria-label="WhatsApp"><Icon name="message" /></a><span className="social-label">Chennai, India</span></motion.div></motion.div></div><HeroVisual /></section>
}

function HeroVisual() {
  return <motion.div className="hero-visual" initial={{ opacity: 0, scale: .92 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .9, delay: .2 }}><div className="orb orb-main" /><div className="orb orb-small" /><span className="float-symbol symbol-one">&lt;/&gt;</span><span className="float-symbol symbol-two">✦</span><span className="float-symbol symbol-three">{`{ }`}</span><div className="code-window"><div className="window-top"><span /><span /><span /><small>akaash.dev / creative-lab</small></div><div className="code-body"><div><i>const</i> <b>developer</b> <strong>=</strong> {'{'}</div><div className="indent"><label>name:</label> <span>'Akaash V'</span>,</div><div className="indent"><label>focus:</label> <span>'Web + AI'</span>,</div><div className="indent"><label>available:</label> <mark>true</mark>,</div><div>{'}'}</div><div className="code-cursor">_</div></div></div><div className="tech-card react-card"><span className="tech-logo react-logo">⚛</span><small>React.js</small><b>72%</b></div><div className="tech-card python-card"><span className="tech-logo python-logo">⌘</span><small>Python + ML</small><b>76%</b></div><div className="ai-card"><span className="ai-dot" /><div><b>AI / ML</b><small>building ideas</small></div><Icon name="sparkles" size={16} /></div></motion.div>
}

function About() { return <section className="page-section section about" id="about"><div className="about-grid"><div><SectionHeading kicker="01 / ABOUT" title="Turning curiosity into useful products." intro="Aspiring and dedicated Computer Science graduate focused on web development, artificial intelligence and practical software solutions. I enjoy transforming ideas into useful, responsive and visually engaging digital products. I continuously learn new technologies and work on real-world projects to improve my development and problem-solving skills." /><a className="text-link" href="#contact">Let's work together <Icon name="arrow" size={17} /></a></div><motion.div className="stats-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true }}><div className="stat-feature"><span>Currently exploring</span><strong>the space where<br /><em>design meets logic.</em></strong><div className="stat-line" /></div>{data.stats.map(([number, label]) => <motion.div className="stat" key={label} variants={reveal}><strong><Counter value={number} /></strong><span>{label}</span></motion.div>)}</motion.div></div></section> }

function Skills() { return <section className="page-section section" id="skills"><SectionHeading kicker="02 / TOOLKIT" title="Tools I use to make things happen." intro="A growing toolkit built through hands-on projects, experimentation and a healthy curiosity for what comes next." /><div className="skills-layout"><motion.div className="skills-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .15 }}>{data.skills.map(([name, type, level, icon]) => <motion.div className="skill" variants={reveal} key={name}><div className={`skill-icon icon-${icon}`}><Icon name={icon === 'ml' ? 'brain' : icon === 'iot' ? 'zap' : icon === 'git' ? 'layers' : icon} size={18} /></div><div className="skill-info"><div><b>{name}</b><span>{type}</span></div><div className="bar"><i style={{ width: `${level}%` }} /></div></div><strong>{level}%</strong></motion.div>)}</motion.div><div className="soft-panel"><span className="kicker">SOFT SKILLS</span><h3>Good work is<br /><em>great communication.</em></h3><div className="soft-list">{data.softSkills.map(skill => <span key={skill}><Icon name="check" size={15} />{skill}</span>)}</div></div></div></section> }

function Services() { return <section className="page-section section section-muted" id="services"><SectionHeading kicker="03 / SERVICES" title="What I can do for you." intro="From the first sketch to a polished launch, I help turn ambitious ideas into clear, useful digital experiences." /><motion.div className="service-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .12 }}>{data.services.map(([title, description, icon], index) => <motion.article className="service-card" variants={reveal} whileHover={{ y: -7 }} key={title}><div className="card-index">0{index + 1}</div><div className="service-icon"><Icon name={icon} /></div><h3>{title}</h3><p>{description}</p><a href="#contact" aria-label={`Discuss ${title}`}><Icon name="arrow" size={17} /></a></motion.article>)}</motion.div></section> }

function ProjectCard({ project }) { return <motion.article className={`project-card ${project.accent}`} variants={reveal} whileHover={{ y: -8 }}><div className="project-preview"><div className="preview-grid" /><div className="preview-label"><span /><b>{project.category}</b>{project.status && <em>{project.status}</em>}</div><div className="dashboard-ui"><div className="dash-header"><span>Good morning, Akaash</span><i /></div><div className="dash-values"><div><small>Today's generation</small><b>8.42 <i>kWh</i></b></div><div><small>Efficiency</small><b>94.8 <i>%</i></b></div></div><div className="dash-chart"><span /><span /><span /><span /><span /><span /><span /></div></div></div><div className="project-content"><div className="project-top"><span className="kicker">{project.category}</span><div className="project-links"><a href="#contact">{project.action}</a><a href="https://github.com">GitHub <Icon name="arrow" size={14} /></a></div></div><h3>{project.title}</h3><p>{project.description}</p><div className="tech-tags">{project.tech.map(tech => <span key={tech}>{tech}</span>)}</div><div className="feature-list">{project.features.map(feature => <span key={feature}><Icon name="check" size={13} />{feature}</span>)}</div></div></motion.article> }
function Projects() { return <section className="page-section section" id="projects"><SectionHeading kicker="04 / SELECTED WORK" title="A few things I've been building." intro="Practical projects with thoughtful interfaces, useful data and room to grow." /><motion.div className="project-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .1 }}>{data.projects.map(project => <ProjectCard project={project} key={project.title} />)}<motion.article className="coming-card" variants={reveal}><div className="coming-plus">+</div><span className="kicker">UP NEXT</span><h3>More projects<br /><em>coming soon...</em></h3><p>New experiments are always in progress.</p></motion.article></motion.div></section> }

function Timeline({ education = false }) { const items = education ? [['Bachelor of Engineering', 'Computer Science & Technology', 'Prince Dr K Vasudevan College of Engineering & Technology', '2022 – 2026', 'CGPA: 7.6'], ['Higher Secondary Education', '', 'A.R.G Academy Matriculation Higher Secondary School', '2021 – 2022', 'Percentage: 64.17']] : [['Machine Learning Intern', 'Python · Predictive Analytics', 'Worked on machine learning model development and optimization using Python. Assisted with data preprocessing, feature engineering and model evaluation while collaborating on real-time predictive analytics projects.', 'June 2025 – August 2025', 'Internship']]; return <div className="timeline">{items.map((item, index) => <motion.div className="timeline-item" variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true }} key={item[0]}><div className="timeline-dot" /><div className="timeline-year">{item[3]}</div><div className="timeline-card"><span className="kicker">{item[4]}</span><h3>{item[0]}</h3><b>{item[1]}</b><p>{item[2]}</p></div></motion.div>)}</div> }
function Experience() { return <section className="page-section section section-muted" id="experience"><SectionHeading kicker="05 / EXPERIENCE" title="Where I learned by doing." /><Timeline /></section> }
function Education() { return <section className="page-section section" id="education"><SectionHeading kicker="06 / EDUCATION" title="The foundation underneath it all." /><Timeline education /></section> }
function WhyHire() { return <section className="page-section section why" id="why"><div className="why-intro"><span className="kicker">07 / THE DIFFERENCE</span><h2>Why work<br /><em>with me?</em></h2></div><motion.div className="why-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true }}>{data.whyHire.map(([title, description, number]) => <motion.div className="why-card" variants={reveal} key={title}><span>{number}</span><h3>{title}</h3><p>{description}</p></motion.div>)}</motion.div></section> }

function Contact() { const [sent, setSent] = useState(false); const [error, setError] = useState(''); const submit = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!form.get('name') || !form.get('email') || !form.get('message')) { setError('Please fill in your name, email and message.'); return } setError(''); setSent(true); event.currentTarget.reset() }; return <><section className="cta-band"><div className="cta-glow" /><span className="kicker">LET'S MAKE SOMETHING USEFUL</span><h2>Have an idea?<br /><em>Let's build it together.</em></h2><p>Whether you need a website, dashboard, business application or AI/ML project, let's turn your idea into a working digital solution.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Start a Project <Icon name="arrow" size={17} /></a><a className="button button-light" href={`mailto:${data.email}`}>Contact Me <Icon name="mail" size={17} /></a></div></section><section className="page-section section contact" id="contact"><div><SectionHeading kicker="08 / CONTACT" title="Let's work together." intro="Have a project in mind, or just want to say hello? My inbox is open." /><div className="contact-details"><a href={`mailto:${data.email}`}><span><Icon name="mail" /></span><div><small>Email</small><b>{data.email}</b></div></a><a href={`tel:${data.phone}`}><span><Icon name="phone" /></span><div><small>Phone</small><b>{data.phone}</b></div></a><div><span><Icon name="globe" /></span><div><small>Location</small><b>{data.location}</b></div></div></div></div><form className="contact-form" onSubmit={submit} noValidate><div className="form-row"><label>Name<input name="name" placeholder="Your name" /></label><label>Email<input name="email" type="email" placeholder="you@company.com" /></label></div><label>Project Type<select name="projectType"><option>Website Development</option><option>Dashboard Development</option><option>AI / Machine Learning</option><option>Something else</option></select></label><label>Message<textarea name="message" rows="5" placeholder="Tell me a little about your idea..." /></label>{error && <p className="form-message error">{error}</p>}{sent && <p className="form-message success">Thanks, Akaash will get back to you soon.</p>}<button className="button button-primary" type="submit">Send Message <Icon name="arrow" size={17} /></button><a className="whatsapp-link" href="https://wa.me/919578448321"><Icon name="message" size={17} /> Prefer WhatsApp? Start a chat</a></form></section></> }
function Footer() { return <footer><div className="footer-top"><a className="logo" href="#home">Akaash<span>.dev</span></a><p>Building digital experiences with code, creativity and curiosity.</p><div className="social-row"><a href="https://github.com" aria-label="GitHub"><Icon name="github" /></a><a href="https://linkedin.com" aria-label="LinkedIn"><Icon name="linkedin" /></a><a href={`mailto:${data.email}`} aria-label="Email"><Icon name="mail" /></a><a href="https://wa.me/919578448321" aria-label="WhatsApp"><Icon name="message" /></a></div></div><div className="footer-bottom"><span>© 2026 Akaash V. All Rights Reserved.</span><div><a href="#home">Home</a><a href="#about">About</a><a href="#services">Services</a><a href="#projects">Projects</a><a href="#contact">Contact</a></div></div></footer> }

export default function App() { return <><Navbar /><main><Hero /><About /><Skills /><Services /><Projects /><Experience /><Education /><WhyHire /><Contact /></main><Footer /></> }
